"""Checkpoint save/load with config-hash resume guard."""

from __future__ import annotations

import pickle
from pathlib import Path
from typing import Any, Mapping

from raven_mcs.utils.hashing import config_hash
from raven_mcs.utils.manifest import assert_resume_config_hash, load_manifest
from raven_mcs.utils.paths import checkpoint_path, latest_checkpoint
from raven_mcs.utils.seed import capture_rng_state, restore_rng_state
from raven_mcs.utils.serialization import atomic_write_bytes


def save_window_checkpoint(
    run_dir: Path,
    *,
    window_r: int,
    state: Mapping[str, Any],
    config: Mapping[str, Any],
    include_rng_state: bool = True,
) -> Path:
    """Atomically save arbitrary trusted Python/Torch state for one window."""
    manifest = load_manifest(run_dir)
    payload = {
        "checkpoint_version": 1,
        "window_r": int(window_r),
        "config_hash": config_hash(config),
        "run_hash": manifest["run_hash"],
        "state": dict(state),
        "rng_state": capture_rng_state() if include_rng_state else None,
    }
    path = checkpoint_path(run_dir, window_r)
    atomic_write_bytes(path, pickle.dumps(payload, protocol=pickle.HIGHEST_PROTOCOL))
    return path


def load_checkpoint_for_resume(
    run_dir: Path,
    config: Mapping[str, Any],
    *,
    restore_rng: bool = True,
) -> dict[str, Any] | None:
    """
    Load latest checkpoint if present.

    Raises RuntimeError if resume config hash does not match the run manifest.
    """
    run_dir = Path(run_dir)
    manifest_path = run_dir / "manifest.json"
    if not manifest_path.exists():
        return None
    assert_resume_config_hash(run_dir, config)
    ckpt = latest_checkpoint(run_dir)
    if ckpt is None:
        return None
    # Checkpoints are trusted local artifacts generated by this repository.
    with ckpt.open("rb") as f:
        payload = pickle.load(f)
    if payload.get("config_hash") != config_hash(config):
        raise RuntimeError(
            f"Resume refused: checkpoint config hash mismatch at {ckpt}"
        )
    manifest = load_manifest(run_dir)
    if payload.get("run_hash") != manifest.get("run_hash"):
        raise RuntimeError(f"Resume refused: checkpoint run hash mismatch at {ckpt}")
    if restore_rng and payload.get("rng_state") is not None:
        restore_rng_state(payload["rng_state"])
    return payload


def run_already_succeeded(run_dir: Path) -> bool:
    """True if metrics_run.json exists and manifest has no failure."""
    run_dir = Path(run_dir)
    metrics = run_dir / "metrics_run.json"
    if not metrics.exists():
        return False
    try:
        man = load_manifest(run_dir)
    except FileNotFoundError:
        return False
    return (
        man.get("end_time") is not None
        and man.get("hard_gate_status") in {"PASS", "N/A"}
        and man.get("failure_reason") in (None, "", "null")
    )
